apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name      : backend
  namespace : argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: argocd
  source:
    path          : "guestbook"
    repoURL       : "https://github.com/muxe1/argocd-example-apps"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
